{{- if (include "kubeflow.katib.controller.enabledWithCertManager" . )}}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    {{- include "kubeflow.katib.controller.labels" . | nindent 4 }}
  name: {{ include "kubeflow.katib.controller.certName" . }}
  namespace: {{ include "kubeflow.namespace" . }}
spec:
  isCA: true
  commonName: {{ .Values.katib.controller.name }}.{{ .Release.Namespace }}.svc
  dnsNames:
    - {{ .Values.katib.controller.name }}.{{- .Release.Namespace }}.svc
    - {{ .Values.katib.controller.name }}.{{- .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: katib-selfsigned-issuer
  secretName: katib-webhook-cert
{{- end }}